# Use the official httpd image as the base image
FROM httpd:latest

# Copy the static HTML file into the Apache document root directory
COPY index1.html /usr/local/apache2/htdocs/

# Expose port 80 to allow external access to the Apache server
EXPOSE 80
